[project]
name = "nir-pit"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = [
    "matplotlib==3.10.8",
    "numpy==2.4.1",
    "simpleitk==2.5.3",
]
